version: '2.1'

services:
  demoemrserver:
    image: demoemrserver
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9006:9006
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 app.js